config/routes.rb
Rails.application.routes.draw do
  get 'admin1/index'
  get 'submit/index'
  get 'faq/index'
  get 'forgetpass/index'
  get 'contact/index'
  get 'about/index'
  get 'home/index'
  #get 'admin/index'
  #get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users

  get "admin" => "admin#index"
  controller :sessions do
  get 'login' => :new
  post 'login' => :create
  delete 'logout' => :destroy
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/admin1_controller.rb
class Admin1Controller < ApplicationController
  def index
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/submit_controller.rb
class SubmitController < ApplicationController
  def index

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:new, :create, :index]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new

  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity, notice: 'You are not Admin to Update' }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { render :show, status: :ok, location: @user }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin1_helper.rb
module Admin1Helper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/forgetpass_helper.rb
module ForgetpassHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/submit_helper.rb
module SubmitHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1> <br><br><br><br><br><br><center>hello, Welcome to Corequadlabs Pvt. Ltd.<center> </h1>
<link href="//vjs.zencdn.net/7.3.0/video-js.min.css" rel="stylesheet">
<script src="//vjs.zencdn.net/7.3.0/video.min.js"></script>


<center><b><button onclick="window.location.href = 'https://talky.io/ajinkya'"; style = "Background-color:red; color:white;width:80px;
height:30px;" value="">Go Live</b></center></button>
<br>
<center><%= button_to "Logout", login_path, :method => :get %></center> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  </body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="topnav">
<br>
<h1><font color = "">COREQUADLABS PVT. LTD. </font></h1>
        <nav>
          <ul class="navbar navbar-light bg-light">
            <li><%= link_to "Home", home_index_path %></li>	
	    <li><%= link_to "About Us", about_index_path %></li>
	    <li><%= link_to "Contact Us", contact_index_path %></li>
	    <li><%= link_to "FAQ's", faq_index_path %></li></br>
	    <li><%= link_to "Sign Up", users_path %></li></br>
          </ul>
        </nav>
      </div>
    </header>

    <div class="topnav">
      <%= yield %>
    </div>
</html>
<br><br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>	
<br>
<br>
<br>
<br>
<br>
<br>

<p><div align = "right"> &copy; 2019 Corequadlabs Pvt. Ltd. All Rights Reserved </p>